### PR TITLE
Lcd 016 n002 l

### PR DESCRIPTION
**Pull request by Misca1234**
Updated model of LCD-016N002L
http://www.vishay.com/product?docid=37299"

bild

PS
This also need an update of the schematic because of the A1, K1, A2 and K2 pins
DS

### CODE REVIEW

**Comment by poeschlr** [comment]
You have the pin1 marker near pad 16 not pad 1

**Comment by Misca1234** [comment]
This push consist of two devices, the reason for this 
is that the old symbol "LCD12X2" had LCD-016N002L1" as an alias,
I could not just remvoe this alias becosue travis started to scan LCD12X2 (with errors)
so i had to "fix" LCD12X2 as well.
Which I discovered that LCD12X2 actuallay is actually WC1602A 

So I have 
Fixed LCD-016N002L1
Removed  LCD12X2
Added WC1602A

I have modified symbol, footprint, 3D models

LCD-016N002L1
http://www.vishay.com/docs/37299/37299.pdf

WC1602A
http://dl.btc.pl/kamami_wa/wc1602a0.pdf

bild

bild

**Comment by poeschlr** [comment]
For LCD-016N002L i fear the A and K pins are placed wrong.
lcd-016n002l_measurements1

**Comment by poeschlr** [comment]
The mounting holes of WC1602A have suspicious coordinates.

**Comment by Misca1234** [comment]
ohhh, you have hawk eyesm 
It have been fixed 

bild

**Comment by poeschlr** [comment]
Thanks for your contribution.

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
