### PR TITLE
Added RC1602A

### PR DESCRIPTION
**Pull request by Misca1234**
Pimped up RC1602A, both foot print and 3D model

http://www.raystar-optronics.com/products-category-detail.php?lang=en&ProID=18

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
What about the A/K pins on the left side?
The slot cutouts have the wrong size.
The courtyard should not follow the outline in the cutouts. (All pads of the footprint must be inside the courtyard.)
rc1602a svg

**Comment by Misca1234** [comment]
I was a little uncertain about that courtyard thingy so I let it follow the outline but I fix it

**Comment by Misca1234** [comment]
Like this ?

bild

**Comment by poeschlr** [comment]
The a and k pads are on the wrong side. They should be on the left.

**Comment by Misca1234** [comment]
Fixed 

bild

**Comment by poeschlr** [comment]
The a and k pins are at the wrong position (by 0.03mm)
rc1602a_1 svg

**Comment by Misca1234** [comment]
Fixed

**Comment by poeschlr** [comment]
Thanks

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
