### PR TITLE
Modified according ot new rules

### PR DESCRIPTION
**Pull request by Misca1234**
Here is an updated AG12864E, Ampire
http://www.ampire.com.tw/en/p1-search-list.asp
Do not have the data sheet anymore but i found it here
https://www.digchip.com/datasheets/parts/datasheet/1121/AG-12864E-pdf.php

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
A pin 1 marker is missing on the fab layer.
I would also suggest to add an outline on silk. (offset the fab line by the line width of the silk line and remove parts of this new outline where it would overlap pins.)
screenshot from 2017-06-30 11-21-13

**Comment by Misca1234** [comment]
I will add the Pin 1 marker as in 
https://github.com/KiCad/Displays.pretty/pull/10#issuecomment-312220951

**Comment by Misca1234** [comment]
It looks like this now 
bild

**Comment by poeschlr** [comment]
Looks very nice. To make it even better i would suggest to make the right side of the silk screen hug the display outline.
screenshot from 2017-07-01 11-19-40

**Comment by Misca1234** [comment]
Done, both cutted holes look like this 

bild

**Comment by poeschlr** [comment]
Very good work. Thanks

**Comment by Misca1234** [comment]
Nice, thanks

**Pull request merged**
