### PR TITLE
Added EA_DOGS104X-A

### PR DESCRIPTION
**Pull request by Misca1234**
Display:
EA DOGS104B-A

Aliases: 
EA DOGS104W-A
EA DOGS104N-A

http://www.lcd-module.com/fileadmin/eng/pdf/doma/dogs104e.pdf

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1507

pretty push branch is
https://github.com/KiCad/Displays.pretty/pull/33

packages3D push branch is
https://github.com/KiCad/packages3D/pull/116

packages3D-source push branch is
https://github.com/KiCad/packages3D-source/pull/43

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
Again a very nice contribution. But i noticed some small things.
Do you plan on adding the backlight version? (Similar to the other ea display, the outline is larger in x direction for the backlight version.)

The bottom courtyard line is too far away. (Currently there is a 0.28mm clearance)

**Comment by poeschlr** [comment]
@Misca1234 could you take a look at the courtyard?

**Comment by Misca1234** [comment]
I fixed the bottom section, currently i did not plan to add the backlight version, 
perhaps I pick it up when I am done with the Opto-Device lib

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
