### PR TITLE
Added HDSM-541B and HDSM-543B

### PR DESCRIPTION
**Pull request by Misca1234**
Foot print for 
HDSM-541B and HDSM-543B

Datasheet 
https://docs.broadcom.com/docs/AV02-1588EN

Foot print
https://github.com/KiCad/Displays.pretty/pull/20

Source code
https://github.com/KiCad/packages3D-source/pull/21

3D model in kicad-library
https://github.com/KiCad/kicad-library/pull/1405

3D model in package3D
https://github.com/KiCad/packages3D/pull/83

I narrowed it a little

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
One question on the side: Why is the silkscreen so minimal? Shouldn't we orient the silkscreen on what is used for other devices, such as SOIC, relays or diverse modules? I.e. a fully or partially enclosing rectangle (with a pin1-mark ... This way it is more obvious where to place the part, when hand-assembly the PCB ... and what to expect.

Here are some examples from the lib.
2017-07-11 19_46_37-library browser housings_soic c__development_kicad_share_kicad_modules_housi
2017-05-16 07_48_44-footprint editor no active library
2017-03-07 21_19_50-footprint editor no active library
2017-02-20 08_00_29-footprint editor no active library
2017-02-19 17_04_40-footprint editor no active library

**Comment by Misca1234** [comment]
I can make it longer  if you want, i just took some nice natural number along the X-axis

**Comment by poeschlr** [comment]
The chamfer on the fab layer looks a bit large as well. (now that jan made me aware of this stuff.)

I would suggest a silk layer like this
28080391-28b91f84-666c-11e7-9450-6d43c80b93ec

**Comment by Misca1234** [comment]
I almost got away with it ;)

**Comment by Misca1234** [comment]
Looks like this now 

bild

**Comment by poeschlr** [comment]
Footprints look very nice.
Merging for now. Moving to 7 segment pretty lib can be done in a separate pull request. (I think this would be easier done for all 7 segment displays that have been merged already into the wrong lib.)

**Comment by Misca1234** [comment]
Thanks 
For the CA56 I already moved them to new "Displays_7_Segments.lib"
Alright, when we are done pimping up the existing ones we can move the already wrong ones

**Pull request merged**
