### PR TITLE
footprint for EA DOGXL160 display

### PR DESCRIPTION
**Pull request by Misca1234**
This uses 
https://github.com/KiCad/kicad-library/pull/1323
https://github.com/KiCad/packages3D/pull/54

### CODE REVIEW

**Comment by poeschlr** [comment]
If the line of the fab layer is the part outline, than the pin 1 marker is not visible after assembly.
Maybe turn it by 90 degree counter clock wise such that it is on the outside?

Is there a reason why the courtyard has a very large clearance on the left and right side but a very small clearance on top/bottom (y direction)?

The 3d path should start with $KISYS3DMOD/

Do i understand it correctly that the (only) difference between the backlight version and the normal version is the 3d file?
Normally this clearance should be the same all around (by default 0.25mm unless there is a reason why it should be different.)
On left right the clearance is measured from the outside of the pins (from copper of the pin)
On top/bottom it is measured from the device outline itself.

**Comment by Misca1234** [comment]
I have made the following changes 
Added ${KISYS3DMOD}/ to the 3D path
made the outline at distance 0.25mm
Changed the pin 1 marker

Well, original the idea is was to have two different 3D shapes , one with backlight and one without , but for now, i only start with the one without back light

bild

**Comment by Misca1234** [comment]
Here you can see how it looks like with and without back light

bild

**Comment by evanshultz** [comment]
@Misca1234 
Don't we want footprints with and without backlights? Otherwise we can't have both 3D models. It's fine with me to review and merge both here, together, as they should be the same except for the footprint name and 3D model name. The symbol should be able to match either footprint. Am I confused?

**Comment by evanshultz** [comment]
Also, please put `${KISYS3DMOD}/` in front of the 3D model path. So it will be `${KISYS3DMOD}/Displays...`.

**Comment by Misca1234** [comment]
Mmm, that get messed up a lot, it does not help if I change KISYS3DMOD in the main window and other places, sometimes the absolute path sneaks in now and and then. I have a couple "magic" steps I must do every time, such as clicking on path etc. to get kicad accepting it.

> 
Don't we want footprints with and without backlights? Otherwise we can't have both 3D models. It's fine with me to review and merge both here, together, as they should be the same except for the footprint name and 3D model name. The symbol should be able to match either footprint. Am I confused?

The tours around this display have been a lot, from beginning the idea was the following.

Symbol EA_DOGXL160-7 -> footprint EA_DOGXL160-7 -> 3d symbol EA_DOGXL160-7 (no backlight)
and
Symbol EA_DOGXL160-7_withbacklight -> footprint EA_DOGXL160-7_withbacklight -> 3d symbol EA_DOGXL160-7_withbacklight

On request, the symbol EA_DOGXL160-7 have now been changed in to the symbol with the backlight pins visible so I have to change everything into 

Symbol EA_DOGXL160-7 -> footprint EA_DOGXL160-7 -> 3d symbol EA_DOGXL160-7 (with backlight)
and
Symbol EA_DOGXL160-7_withbacklight -> footprint EA_DOGXL160-7_withbacklight -> 3d symbol EA_DOGXL160-7_withbacklight (with backlight obviously)

**Comment by evanshultz** [comment]
@Misca1234 
I don't know what you mean by "files changed" but when I look at commit 6df37086ced8d5f95f1a5c0f9cb3108218e42c5a (the latest one) I don't see `${KISYS3DMOD}/`:
image

The philosophy for KiCad is use common schematic symbols and multiple footprints. So having a footprint with and without backlight is the way to go. You can name then `EA_DOGXL160-7_Backlight` and `EA_DOGXL160-7`. Please note the capitalization of "Backlight".

To include helpful info here for anyone and everyone involved, the datasheet is at http://www.lcd-module.com/eng/pdf/grafik/dogxl160-7e.pdf.

**Comment by Misca1234** [comment]
That is strange, because the in the folder " Files changed 1 " ontop of this page says "model ${KISYS3DMOD}/Displays.3dshapes/EA_DOGXL160-7.wrl"

But I will do a minor change and re push.

> You can name then EA_DOGXL160-7_Backlight and EA_DOGXL160-7. 
> Please note the capitalization of "Backlight".

I will fix the 3D models after this foor print is in because it have changed so much since start 
(Note that one of the 3D models are already in kicad-library/modules/package3D/Displays.3dshapes)

**Comment by Misca1234** [comment]
BTW, I notice that several other displays in the pretty/Displays.pretty does not meet 
https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention

For example placement of pin 1, should i fix those and push them as well ?

**Comment by poeschlr** [comment]
If you have the time.
I would suggest doing it in a separate pull requests though.

**Comment by evanshultz** [comment]
Thanks @Misca1234!

Here is an image (in the future it's helpful to add/update an image with major changes):
image

Review notes:
- It seems the fab layer is on the pin row for pins 17-32 but extends over the pin row for pins 1-16. The datasheet drawing looks like the PCD extents are right on (but obviously just inside) the row of pins. Your screenshow above shows both sides of the LCD running along the row of pins. As the datasheet drawing may be wrong or misleading, do you have a physical part to look at?
- Silk is only next to the pins. Can silk go around the entire rectangle of the display? (7.3.iv)
- I don't see a silk mark for pin 1 (7.3.vi).
- Silk line width is 0.1mm. Please use 0.12mm since this footprint needs no special deviation (7.3.v).
- This is not critical, but what do you think about adding a rectangle in silk or fab to show the display area?

Can you also submit an identical footprint, but with `EA_DOGXL160-7` changed to `EA_DOGXL160-7_Backlight`? (I believe the footprint is identical when backlight is added, right?) While the 3D models are different, a footprint can only link to one 3D model. Both footprints can be submitted together in this PR since they're so closely linked. Thanks!

And to re-affirm Rene above, both display libraries are in poor shape. Any contributions you are able to make there would be much appreciated. :)

**Comment by Misca1234** [comment]
> It seems the fab layer is on the pin row for pins 17-32 but extends over the pin row for pins 1-16. 
> The datasheet drawing looks like the PCD extents are right on (but obviously just inside) 
> the row of pins. Your screenshow above shows both sides of the LCD running along the row of pins. 
> As the datasheet drawing may be wrong or misleading, do you have a physical part to look at?

Yes, I have the display at work, i check it tomorrow

> I don't see a silk mark for pin 1 (7.3.vi).
It is this one 
bild


Yes, I will fix the back light version as well when this is approved.

**Comment by Misca1234** [comment]
The edge of the PCB is going pretty straight over the pin holes

bild

**Comment by Misca1234** [comment]
Here are both footprints

bild

bild

**Comment by evanshultz** [comment]
@Misca1234 This is looking nice. Thanks! I will take a closer look later.

While KLC requests a silk mark for pin 1 in addition to a square pad shape, in this case the part is keyed by the pin placement so I don't think a silk mark is needed. I didn't think of this earlier. What is the reason for the silk lines by pins 1-3 and 17-32? I'm wondering if they're unneeded.

**Comment by Misca1234** [comment]
oh, nice, perhaps it will be all good soon.

The silk lines at 1-3 and 17-32 is an attempt to mimmick the pin 1 marking mention on the 
https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention
similare for the SMD pattern 
https://raw.githubusercontent.com/wiki/KiCad/kicad-library/images/klc7_3_4_5.png

(I have a faint memory of someone was asking for it and it is mentioned in 
7.3 vi but with the disclaimer "where appropriate")
But i can removed them if they are not needed.

**Comment by evanshultz** [comment]
Once the pin 1 mark at https://github.com/KiCad/Displays.pretty/pull/10#issuecomment-312220951 is settled, please copy that design into this footprint as well.

**Comment by Misca1234** [comment]
Both look like this now
bild

**Comment by evanshultz** [comment]
@Misca1234 I saw in a recent commit you marked pin 1 on a similar display with a `|_` shape (like the letter "L"). This also matches a lot of pin 1 marks I now see on THT parts in KiCad. Can you please make that change here too?

**Comment by poeschlr** [comment]
And include the outermost outline on silk. (A bit outside of the fab layer, broken up where pads are located.)

**Comment by Misca1234** [comment]
Huh, should I change to the L shape on all other displays as well ?

**Comment by Misca1234** [comment]
Here we go

bild


bild

**Comment by poeschlr** [comment]
@Misca1234 wrote:
> Huh, should I change to the L shape on all other displays as well ?

Only if it makes sense. For this footprint the pin 1 marker in L shape is still visible after assembly. For others this might not be the case.

I would suggest a bit larger clearance between the pin 1 marker and the center of the drill though. I think a lot of users will use pin headers to connect the pcb with the display. A pin header has a body of 1.27mm "around" the center of the hole. So having the L with distance 1.35mm from the center of the hole might be a better choice. (Maybe test it and if it looks ok to you it will look ok for everyone.)
27839409-4bfdfa94-60f1-11e7-8fa4-f4bb8c86c0a1

**Comment by Misca1234** [comment]
Like this 

bild

**Comment by poeschlr** [comment]
It seems i was blind when i first checked this footprint. I fear the pin spacing in x direction is wrong. It should be 60.96 currently it is 60.66
This would mean the fab outline should move to the right by 0.15mm, the right pins should move 0.3mm to the right. (should be easily done with the move exact tool.)

Also the version with backlight seems to be larger in x direction than the version without.

At least according to the [datasheet](http://www.lcd-module.com/eng/pdf/grafik/dogxl160-7e.pdf) sketch on page 8.

And i would also suggest a minor modification of the silk outline on the right side. I would remove the line along the pins. (looks a bit odd)
screenshot from 2017-07-04 20-48-49

**Comment by Misca1234** [comment]
But if you zoom into the 
http://www.lcd-module.com/eng/pdf/grafik/dogxl160-7e.pdf
The 60.96 measurement is from the outside edges of the pins, so I would argue for that the distance to the middle of the pins is still 60.66 but only the fab layer should be moved 0.15 mm

**Comment by Misca1234** [comment]
The look like this now

bild

bild

bild

bild

**Comment by poeschlr** [comment]
The center pin distance is definitely 60.96mm (2.4").
Why?
If you look closely at the sketch on page 8, you see that the measurement (marked in green) is showing the center to center distance. See detail in cyan (Dimension marker points to middle of pin.)

In the backlight version 60.96mm (2.4") is given as the center to center distance for the holes. If you are correct and the backlight is an extension to the normal display, then this distance should be the same for both the non backlight version and the backlight version.

dogxl160-7e_dimensions

**Comment by Misca1234** [comment]
Yes, you are right, I moved it 0.3 mm 

bild

bild

bild

bild

**Comment by poeschlr** [comment]
Ok the pin placement looks ok now.

For the non back-light version the courtyard should have a 0.25mm clearance to the copper rings of the pads in y direction. (On the right side the courtyard line is above copper. Left side is only a bit off.)
The courtyard rectangle should be from (-1.01, -20.2) to (61.97, 58.3).

For the backlight version there is only a slight error in the courtyard. The correct rectangle should be from (-1.92, -20.2) to (62.58, 58.3)

**Comment by evanshultz** [comment]
@poeschlr You've done the latest review on this, so please go ahead and merge if you're happy.

**Comment by poeschlr** [comment]
Looks good now. Thanks for your continued contributions.

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
