### PR TITLE
Added EA_eDIPTFT43-A

### PR DESCRIPTION
**Pull request by Misca1234**
Display EA eDIPTFT43-A (and it's alias EA eDIPTFT43-ATP and EA eDIPTFT43-ATS)

http://www.lcd-module.com/fileadmin/eng/pdf/grafik/ediptft43-ae.pdf

kicad-library push branch is 
https://github.com/KiCad/kicad-library/pull/1494

pretty push branch is 
https://github.com/KiCad/Displays.pretty/pull/26

packages3D push branch is 
https://github.com/KiCad/packages3D/pull/109

packages3D-source push branch is 
https://github.com/KiCad/packages3D-source/pull/36

bild

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
That is right, i will split them into two footprints,.

The numbering I found was this 
bild


From http://www.lcd-module.com/support/application-note/ea-edip-serie.html?no_cache=1&sword_list%5B0%5D=ea&sword_list%5B1%5D=ediptft43a

I got the datasheet for the Programmer board with USB EA 9777-1USB 
http://www.lcd-module.com/pdf/zubehoer/9777-1.pdf
which had this picture

bild

Shall I ask them explicitly about the pins ?

**Comment by Misca1234** [comment]
Added the ATC variant on request in 
https://github.com/KiCad/kicad-library/pull/1494


bild

**Comment by Misca1234** [comment]
Added more info in documentation filed and added F.Silk display area outline
See 
https://github.com/KiCad/Displays.pretty/pull/25

bild

bild

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
