### PR TITLE
Updated HDSP-48xx, Added HDSP-4830, HDSP-4832, HDSP-4836, HDSP-4840, …

### PR DESCRIPTION
**Pull request by Misca1234**
Updated HDSP-48xx
Added HDSP-4830, HDSP-4832, HDSP-4836, HDSP-4840, HDSP-4850, HLCP-J100

https://docs.broadcom.com/docs/AV02-1798EN

The reason for keeping HDSP-48xx is for backward kompability
The reason for creating the new ones is to make specific 3D models wih correct colour

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
For footprints where the pin 1 is in a corner, making the pin 1 marker a simple chamfer is the preferred way.
You forgot to add a pin 1 marker to the silk layer.
screenshot from 2017-07-01 11-06-13

**Comment by Misca1234** [comment]
Ok, fixing it

**Comment by Misca1234** [comment]
Here we go

bild

**Comment by poeschlr** [comment]
Why did you change the 3d path to display.3dshapes?
The 3d lib should be named the same as the footprint lib. (If it currently is not, it should be renamed.)

**Comment by poeschlr** [comment]
I opened an issue about this.
https://github.com/KiCad/kicad-library/issues/1369

**Comment by Misca1234** [comment]
I thought I should use how it is today but I can change it to Displays


PS
This mean that the 3D models I push in repository package3D should be placed in Displays.3dshapes as well ?
DS

**Comment by poeschlr** [comment]
Yes the packages3d model directory should be named the same as the one in the main library repo.
Both of them should be named Displays.3dshapes

**Comment by poeschlr** [comment]
What is the purpose of the 48xx footprint? You have the footprint for all versions including a 3d model, there might be no need for a generic footprint without 3d model.

**Comment by Misca1234** [comment]
I kept 48xx for backward compability, so old schematics should still "work" so to speak.

But I remove the 48XX

**Comment by poeschlr** [comment]
Ok i think leafing it does not hurt. Thanks

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
