### PR TITLE
Footprint lm16255

### PR DESCRIPTION
**Pull request by Misca1234**
This is the pimped up foot print for LM16255
http://www.datasheetlib.com/datasheet/259542/lm16255_sharp-electronics.html

Image here
http://az343058.vo.msecnd.net/productlargeimages/63853ccd98714d7792ac4bc8872934bd.jpg

bild

bild

### CODE REVIEW

**Comment by evanshultz** [comment]
@Misca1234 Thanks for the continued contributions!

Just one quick note for now: this appears to be an atypical way to mark pin 1 from what I've seen in the libraries. Can you change the mark to look like the letter `L` around pin 1?

**Comment by poeschlr** [comment]
@evanshultz i don't really see how an L shaped pin 1 marker can be used here. Would you care to make a quick sketch. (Take the screenshot and use any graphical editor to show what you mean. I use inkscape for such tasks.)

**Comment by poeschlr** [comment]
Some measurements are wrong.
lm16255

**Comment by evanshultz** [comment]
I was thinking to remove the parallel silk line and add something like this:
image

 The parallel lines are easy to get covered up by nearby parts or ref des, and this "L" style matches a number of other pin 1 markings of footprints in the library.

**Comment by Misca1234** [comment]
I can change it to an L, but all footprints "nowdays" have a line and not a L any more because I have remade them all and all have a line.
(except for the EA-DOG one because it was requested to be changed into a L.)

If you really want an L to this one, I would guess that all footprints should have an L , whichmeans i have to re push all foot prints again.

**Comment by Misca1234** [comment]
I have corrected the 0.04 mm error, you have decide if you want an L or a line for Pin 1 marker

**Comment by Misca1234** [comment]
Remember also, it is difficult to place these LCD in the wrong direction because they are so enormous big compared to other component and the silk line marking the area for the LCD will somewhat guide the mounting.

**Comment by poeschlr** [comment]
Somehow the fixing of the mounting holes positions went bad. The lower left hole is not on the correct position. It should be on (-36.78, 37.46)

lm16255_2 svg

**Comment by Misca1234** [comment]
I have no idea why that hole moved, but now it is back in place

**Comment by poeschlr** [comment]
Looks good now. Thanks for your continued effort.

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
