### PR TITLE
Added CA56-12 displays

### PR DESCRIPTION
**Pull request by Misca1234**
Added 
CA56-12CGKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12CGKWA(Ver.9A).pdf

CA56-12EWA
http://www.kingbrightusa.com/images/catalog/SPEC/CA56-12EWA.pdf

CA56-12SEKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12SEKWA(Ver.7A).pdf

CA56-12SURKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12SURKWA(Ver.8A).pdf

CA56-12SYKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12SYKWA(Ver.6A).pdf

to
modules/packages3d/Displays.3dshapes

The existing Cx56-12 was a CA56-12EWA 

Removed
modules/packages3d/Displays_7-Segment.3dshapes/Cx56-12.fcstd
modules/packages3d/Displays_7-Segment.3dshapes/Cx56-12.wrl

kicad-libray
https://github.com/KiCad/kicad-library/pull/1413

Displays.pretty
https://github.com/KiCad/Displays.pretty/pull/22

packages3D
https://github.com/KiCad/packages3D/pull/85

packages3D-source
https://github.com/KiCad/packages3D-source/pull/22

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
I would reduce the pad sizes a bit. 
I would say 1.54 should be a good value (0.27mm annular ring should be enough.) This way there is space for a trace between the pads. (1mm should be more than enough. space for a trace.)
At most i would use 1.84mm for the pad size which would leave 0.7mm pad to pad clearance (would be enough for 0.25mm pad to trace clearance and a 0.2mm trace.)

The courtyard clearance is not uniform all around. should be 0.25mm relative to the fab layer
The resulting rectangle would be: (-2.13, -19.05)(17.37, 31.75)

All footprints are missing the pin 1 marker on fab and the outline on silk.
screenshot from 2017-07-13 11-04-45

**Comment by Misca1234** [comment]
The all look like this now

Added three new because i removed the aliases in the symbols

 
bild

**Comment by poeschlr** [comment]
What about the silk outline?

**Comment by Misca1234** [comment]
Yoy are right, I am to stressed, I am leaving for a week in Egypt tomorrow

**Comment by Misca1234** [comment]
They all look like this now 

bild

**Comment by poeschlr** [comment]
Why the secondary silk line on the right?

**Comment by Misca1234** [comment]
Removed

**Comment by Misca1234** [comment]
Closing this push,  poeschlr  wants them into the Displays_7-Segment.pretty directory instead, 
see https://github.com/KiCad/Displays_7-Segment.pretty/pull/5 for comment and new push

**Pull request closed without merging**
