### PR TITLE
3 d hdsm 441 b hdsm 443 b 2

### PR DESCRIPTION
**Pull request by Misca1234**
This is the first of a series of segment displays

I placed the 3D model into Displays.3dshapes because i guessed that the directory 
"Displays_7-Segment.3dshapes" would be removed and all displays goes into "Displays.3dshapes"

Foot print for 
HDSM-441B and HDSM-413B

Datasheet 
https://docs.broadcom.com/docs/AV02-1589EN

Foot print
https://github.com/KiCad/Displays.pretty/pull/19

Source code
https://github.com/KiCad/packages3D-source/pull/20

3D model in kicad-library
https://github.com/KiCad/kicad-library/pull/1403

3D model in package3D
https://github.com/KiCad/packages3D/pull/82

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you add a description to the documentation field (Aside from the datasheet)

**Comment by poeschlr** [comment]
The courtyard clearance looks quite large is there a reason for that?

**Comment by Misca1234** [comment]
Let me check the courtyard

**Comment by Misca1234** [comment]
Documentation line look like 
"2 Digit 7 segemnt blue LED, right hand decimal, https://docs.broadcom.com/docs/AV02-1589EN"

Changed the courtyard to distance 0.25 mm

bild

**Comment by poeschlr** [comment]
Courtyard is not symmetrical in y direction. The top side has a much larger clearance than everything else.

**Comment by Misca1234** [comment]
Now so

bild

**Comment by poeschlr** [comment]
The (right) courtyard line now has the coordinates (start 9.28 -10.08) (end 9.28 10.15)
Why -10.08 at the top and 10.15 at the bottom? The absolute value should be the same for both.

**Comment by Misca1234** [comment]
I guess I rounded the numbers in each directions or something, one sec

**Comment by Misca1234** [comment]
The reason was becaouse the F.silk lines was not on the same heights

**Comment by Misca1234** [comment]
Now So

**Comment by poeschlr** [comment]
Looks good now. Thanks.

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
