### PR TITLE
Updated HY160E

### PR DESCRIPTION
**Pull request by Misca1234**
Updated version of HY1602E
I could not find the original site for the data sheet, the closest was 
av displays homepage but when clicking on the url my browser warned me about the server 
the url pointed to (it was known to inject harmful code)
So here is the url that was in the orignal footprint

http://www.icbank.com/data/ICBShop/board/HY1602E.pdf

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
Is there a reason for the mounting holes having a pin number? Do they need to be plated through holes? (Yes i know, for some reason i did not see this in the other footprint i just merged.)

**Comment by Misca1234** [comment]
The LCD's are mounted on a PCB, which in turn have plated holes, so my only guess is that you must solder a rack of needles on the mother pcb which then are connecting to the LCD's PCB's plated holes,

Here is a typical image of these types of LCD's 
http://www.wincomlcd.com/pic/WC1602A(BW).jpg

**Comment by poeschlr** [comment]
I mean the 4 holes with pin number 0
I think they might be for something like this:
image

**Comment by Misca1234** [comment]
Aha, those, sorry, no, I can not see any reason for the numbering, they was in the original footprint so I kept them, but i will remove them now

**Comment by Misca1234** [comment]
Looks like this now 

bild

**Comment by poeschlr** [comment]
Thanks for contributing.

**Comment by Misca1234** [comment]
No problem it is fun

**Pull request merged**
