### PR TITLE
Added EA eDIPTFT70-XXX

### PR DESCRIPTION
**Pull request by Misca1234**
Display EA eDIPTFT70-A (and it's alias EA eDIPTFT70-ATP and EA eDIPTFT70-ATC)

http://www.lcd-module.com/fileadmin/eng/pdf/grafik/ediptft70-ae.pdf

kicad-library push branch is 
https://github.com/KiCad/kicad-library/pull/1500

pretty push branch is 
https://github.com/KiCad/Displays.pretty/pull/28

packages3D push branch is 
https://github.com/KiCad/packages3D/pull/111

packages3D-source push branch is 
https://github.com/KiCad/packages3D-source/pull/38

bild

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

looks great!

I have one request/suggestion though: Would you add another rectangle to F.Fab, indicating the actual display area. I think that might help, when positioning additional components on the PCB, which should be aligned with the display.

Best,
JAN

**Comment by Misca1234** [comment]
Something like this ?

bild

**Comment by jkriege2** [comment]
Yes like that ... which layer did you choose? It should be on F.Fab I think!
JAN

**Comment by Misca1234** [comment]
it is on silk, I change it

**Comment by jkriege2** [comment]
Nice work!
Thanks,
JAN

**Comment by Misca1234** [comment]
Changed to F.Fab

**Pull request merged**
